version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      npm-weekly: { patterns: ["*"] }
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    groups:
      actions-weekly: { patterns: ["*"] }
    open-pull-requests-limit: 3
