// Generated by scripts/generate-museum-registry.mjs. Do not edit.
import type { ComponentType } from "react";
import type { MuseumExhibitV1 } from "../core/MuseumExhibitV1";

export type MuseumExhibitModule = {
  manifest: MuseumExhibitV1;
  Scene: ComponentType<{ active: boolean; reducedMotion: boolean }>;
};

export const museumExhibits: readonly MuseumExhibitModule[] = [

];
