// Generated by scripts/generate-museum-registry.mjs. Do not edit.
import type { ComponentType } from "react";
import type { MuseumExhibitV1 } from "../core/MuseumExhibitV1";
import { validateMuseumExhibitV1 } from "../core/MuseumExhibitV1";
import { manifest as manifest0 } from "../exhibits/call-of-duty/manifest";
import { ExhibitScene as Scene0 } from "../exhibits/call-of-duty/ExhibitScene";
import { manifest as manifest1 } from "../exhibits/halo/manifest";
import { ExhibitScene as Scene1 } from "../exhibits/halo/ExhibitScene";
import { manifest as manifest2 } from "../exhibits/obsidian-vault/manifest";
import { ExhibitScene as Scene2 } from "../exhibits/obsidian-vault/ExhibitScene";
import { manifest as manifest3 } from "../exhibits/pokemon-cards/manifest";
import { ExhibitScene as Scene3 } from "../exhibits/pokemon-cards/ExhibitScene";
import { manifest as manifest4 } from "../exhibits/pokemon-game/manifest";
import { ExhibitScene as Scene4 } from "../exhibits/pokemon-game/ExhibitScene";
import { manifest as manifest5 } from "../exhibits/star-wars-game/manifest";
import { ExhibitScene as Scene5 } from "../exhibits/star-wars-game/ExhibitScene";

export type MuseumExhibitModule = {
  manifest: MuseumExhibitV1;
  Scene: ComponentType<{ active: boolean; reducedMotion: boolean }>;
};

export const museumExhibits: readonly MuseumExhibitModule[] = [
  { manifest: validateMuseumExhibitV1(manifest0), Scene: Scene0 },
  { manifest: validateMuseumExhibitV1(manifest1), Scene: Scene1 },
  { manifest: validateMuseumExhibitV1(manifest2), Scene: Scene2 },
  { manifest: validateMuseumExhibitV1(manifest3), Scene: Scene3 },
  { manifest: validateMuseumExhibitV1(manifest4), Scene: Scene4 },
  { manifest: validateMuseumExhibitV1(manifest5), Scene: Scene5 },
];
