// Generated by scripts/generate-museum-registry.mjs. Do not edit.
import { createElement, type ComponentType } from "react";
import type { MuseumExhibitV1 } from "../core/MuseumExhibitV1";
import { validateMuseumExhibitV1 } from "../core/MuseumExhibitV1";
import { manifest as manifest0 } from "../exhibits/call-of-duty/manifest";
import { CallOfDutyExhibitScene as ExhibitScene0 } from "../exhibits/call-of-duty/ExhibitScene";
import { manifest as manifest1 } from "../exhibits/halo/manifest";
import { HaloExhibitScene as ExhibitScene1 } from "../exhibits/halo/ExhibitScene";
import { manifest as manifest2 } from "../exhibits/obsidian-vault/manifest";
import { ObsidianVaultExhibitScene as ExhibitScene2 } from "../exhibits/obsidian-vault/ExhibitScene";
import { manifest as manifest3 } from "../exhibits/pokemon-cards/manifest";
import { PokemonCardsExhibitScene as ExhibitScene3 } from "../exhibits/pokemon-cards/ExhibitScene";
import { manifest as manifest4 } from "../exhibits/pokemon-game/manifest";
import { PokemonGameExhibitScene as ExhibitScene4 } from "../exhibits/pokemon-game/ExhibitScene";
import { manifest as manifest5 } from "../exhibits/star-wars-game/manifest";
import { StarWarsGameExhibitScene as ExhibitScene5 } from "../exhibits/star-wars-game/ExhibitScene";

type MuseumSceneProps = { active: boolean; reducedMotion: boolean };
const Scene0: ComponentType<MuseumSceneProps> = (props) => createElement(ExhibitScene0, { ...props, distance: props.active ? 0 : Number.POSITIVE_INFINITY });
const Scene1: ComponentType<MuseumSceneProps> = (props) => createElement(ExhibitScene1, { ...props, distance: props.active ? 0 : Number.POSITIVE_INFINITY });
const Scene2: ComponentType<MuseumSceneProps> = (props) => createElement(ExhibitScene2, { ...props, distance: props.active ? 0 : Number.POSITIVE_INFINITY });
const Scene3: ComponentType<MuseumSceneProps> = (props) => createElement(ExhibitScene3, { ...props, distance: props.active ? 0 : Number.POSITIVE_INFINITY });
const Scene4: ComponentType<MuseumSceneProps> = (props) => createElement(ExhibitScene4, { ...props, distance: props.active ? 0 : Number.POSITIVE_INFINITY });
const Scene5: ComponentType<MuseumSceneProps> = (props) => createElement(ExhibitScene5, { ...props, distance: props.active ? 0 : Number.POSITIVE_INFINITY });

export type MuseumExhibitModule = {
  manifest: MuseumExhibitV1;
  Scene: ComponentType<MuseumSceneProps>;
};

export const museumExhibits: readonly MuseumExhibitModule[] = [
  { manifest: validateMuseumExhibitV1(manifest0), Scene: Scene0 },
  { manifest: validateMuseumExhibitV1(manifest1), Scene: Scene1 },
  { manifest: validateMuseumExhibitV1(manifest2), Scene: Scene2 },
  { manifest: validateMuseumExhibitV1(manifest3), Scene: Scene3 },
  { manifest: validateMuseumExhibitV1(manifest4), Scene: Scene4 },
  { manifest: validateMuseumExhibitV1(manifest5), Scene: Scene5 },
];
